name: spotify-rfid
services:
    api:
        build:
            context: ../
            dockerfile: ./docker/api.Dockerfile
            args:
                - SSL_CERT=${SSL_CERT}
                - SSL_KEY=${SSL_KEY}
        ports:
            - 8000:8000
        env_file:
            - .dev.env
            - .local.env
